### ISSUE TITLE
Developer locked out when Key wound down

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#37] opened 2013-12-19 10:00 UTC
Key became untouchable when it wound down - and Developer could not escape buggy key as it was locked on.

**Comment by silkymesmeriser** [comment] 2013-12-22 00:01
Wasn't really thinking with this one when I added the RLV for the new outfit lock and strip lock functions and of course to AFK/collapsed too that a full generic @remattach=n or @remattach:objectpoint=n/@detach:objectpoint=n of course has the same effect on the object issuing it as if it had issued @detach=n in the first place.

I have a solution it's less than ideal with the extra memory usage of the attach point list plus tracking state on 39 restrictions in place of 2 but it can be preprocessed out in the final version and of we do hit memory issues I can put it in a separate script if push comes to it I guess though.  Would be easier than it sounds thanks to the linkmessage 320 status messages that RLV.lsl now provides anyway.

**Comment by silkymesmeriser** [comment] 2014-01-09 19:19
This should now be fixed, there was a recurrence of the issue with the wear lock for a while which appears to actually be due to a bug in firestorm, @attachallthis_except and @detachallthis_except are both stored no matter the order they are given in but if you apply the exception after the restriction they exist but do not do anything.  However making sure that the exception is added first is a workaround to the bug and is currently in the key code to work around it in that manner.

Still not sure what happened with the untouchable part but that issue also appears to be resolved so I think that this one is done right?

**Comment by emmamei** [comment] 2014-01-09 19:28
Haven't tested the latest code, but if you've tested it and not found the trouble, must be fixed.

**Comment by emmamei** [comment] 2014-02-07 16:45
This has become expected and routine. The key is completely and utterly locked down even when a developer is wearing it, when the key collapses.

Touch does remain available, and perhaps should not. TP is possible with Lumiya but not Firestorm (both RLV capable viewers).

There is no option for a developer to wind themselves as there is in the usual main menu.

In short, it appears that when the dolly is collapsed that a developer and a normal dolly are treated identically.

**Comment by silkymesmeriser** [comment] 2014-03-18 04:42
Key remains touchable when wound down unless userRLV is used to block it (The latter is expected behaviour and a wontfix).

The addition of the wind button to the main menu and the collapsed menu are both implemented though note this is a TESTER_MODE feature not DEVELOPER_MODE.

The TP issue is bizzare but the key does not currently process or make any distinction between RLV implementations and sends the same syntactically valid RLV API commands irrespective of viewers.  All viewers claiming to be compliant with the RLV specification at least any claiming to support RLV 2.7.0 or above which both of the above do should handle the key RLV commands identically.  Failure to do so would indicate an RLV implementation failure on the part of one of the viewers best we can do is as we have verify the commands are sent correctly and are valid which they are suggesting the key and Firestorm in this instance are both correct, Lumiya may have a bug there.

**Comment by emmamei** [comment] 2014-03-19 03:05
As I normally run now with a Normal Key, I don't have `TESTER_MODE` features, nor `DEVELOPER_MODE` features either. So this is expected: my key does not allow me to self-wind.

Using `userRLV` to block touch is also expected, and adding the appropriate commands to `userRLV` works.

**Closed as completed** 2014-03-19 03:05 UTC
Labels: bug
