### ISSUE TITLE
Attach outfits and then double check results with @getinvworn

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#4] opened 2013-10-30 21:35 UTC
Using @getinvworn is much more respectful of the LL servers than hammering on the servers multiple times.

**Comment by emmamei** [comment] 2014-02-07 16:52
Was this actually completed and implemented? Is it in both keys? Has it been tested?

**Comment by silkymesmeriser** [comment] 2014-02-08 18:30
Same applies here as the other except will need to to reassign to correct milestone if you want to reuse this issue instead of filing a separate one.  You know the other code base better than I do so you would be the better authority so sticking to my area of expertise and knowledge I can tell you the current state in Development.
- Function is implemented and functional, commands are sent once and checked only being retied of the result does not match expectations.
- Successfully retries on failure and correctly caps maximum reties from failures as getinvworn only conforms there has been an error if does not provide the cause which can include external restrictions from other objects or SL/network/client issue beyond a certain number of tries it the chance of success rapidly tends towards zero and ends up being a case of flogging a dead horse so it aborts.

The massive number of potential issues that could be causing the failure makes attempts at auto diagnosis let alone correction of any failures beyond this point kinda a non option.  There is a commercial product out there that merely collects the information together from relevant sources and presents it to the user that wights in at 5 scripts on it's own.  What between the checks on RLV status, the fetching and parsing of the second life grid status, benchmarking and testing for issues with object rezzing, attaching, detaching etc

I can't correct the milestone I guess because you posted this issue can you take care of it?

**Closed as completed** 2014-02-08 22:25 UTC
Labels: bug
